-- =============================================================================
-- KELEME — 0002 Identity: schools, profiles, sessions, audit log
--
-- `auth.users` stays Supabase's; `public.profiles` is our 1:1 extension of it.
-- The two are kept in lockstep by a trigger on auth.users rather than by an
-- application write, so a profile can never be missing for a signed-up user
-- even if the client disconnects mid-registration.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schools
--
-- Free-typed by students at registration but normalised into a real table, so
-- the "reward high-achieving students by school" analytics in spec section 32
-- can group reliably instead of trying to reconcile 400 spellings of one
-- school. `normalized_name` is the dedupe key; `name` keeps the first spelling
-- seen, and admins can correct it without breaking the FK.
-- ---------------------------------------------------------------------------

create table if not exists public.schools (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  normalized_name text generated always as (lower(regexp_replace(trim(name), '\s+', ' ', 'g'))) stored,
  region          text,
  city            text,
  is_verified     boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists schools_normalized_name_key on public.schools (normalized_name);
create index if not exists schools_name_trgm_idx on public.schools using gin (name gin_trgm_ops);

drop trigger if exists schools_touch on public.schools;
create trigger schools_touch before update on public.schools
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Profiles
--
-- Note what is deliberately NOT here: premium status. Entitlements live in
-- their own table with real start/end dates and a source, and the "is this
-- student premium right now" question is answered by
-- public.has_active_entitlement(). Denormalising a boolean onto the profile
-- would create a second source of truth that silently goes stale the moment a
-- subscription lapses at midnight.
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id                  uuid primary key references auth.users (id) on delete cascade,
  full_name           text not null check (length(trim(full_name)) between 2 and 120),
  phone               text not null,
  email               text,
  grade               smallint not null check (grade between 9 and 12),
  school_id           uuid references public.schools (id) on delete set null,
  school_name         text,
  role                public.user_role not null default 'student',

  -- Public identity. `display_name` is only ever shown when the student has
  -- opted in; otherwise the leaderboard falls back to "Student #<public_no>",
  -- which is stable (so a student can recognise their own row) but carries no
  -- personal information.
  display_name        text check (display_name is null or length(trim(display_name)) between 2 and 40),
  leaderboard_opt_in  boolean not null default false,
  public_no           bigint generated by default as identity,

  -- Engagement counters. Maintained exclusively by SECURITY DEFINER functions
  -- from server-verified activity; never writable by the student (see RLS).
  current_streak      integer not null default 0 check (current_streak >= 0),
  longest_streak      integer not null default 0 check (longest_streak >= 0),
  last_activity_date  date,
  total_seconds       bigint not null default 0 check (total_seconds >= 0),

  referral_code       text not null,
  referred_by         uuid references public.profiles (id) on delete set null,

  timezone            text not null default 'Africa/Addis_Ababa',
  avatar_url          text,
  is_suspended        boolean not null default false,
  suspended_reason    text,

  -- Soft deletion: spec section 33 wants an account deletion/deactivation
  -- path that does not cascade a student's contribution history away.
  deactivated_at      timestamptz,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create unique index if not exists profiles_phone_key on public.profiles (phone);
create unique index if not exists profiles_referral_code_key on public.profiles (referral_code);
create unique index if not exists profiles_public_no_key on public.profiles (public_no);
create index if not exists profiles_role_idx on public.profiles (role);
create index if not exists profiles_grade_idx on public.profiles (grade);
create index if not exists profiles_school_idx on public.profiles (school_id);
create index if not exists profiles_referred_by_idx on public.profiles (referred_by);
create index if not exists profiles_created_at_idx on public.profiles (created_at desc);
-- Leaderboard reads are always "opted-in, not suspended, ordered by time".
create index if not exists profiles_leaderboard_idx
  on public.profiles (total_seconds desc)
  where leaderboard_opt_in and not is_suspended and deactivated_at is null;
create index if not exists profiles_name_trgm_idx on public.profiles using gin (full_name gin_trgm_ops);

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Role / grade helpers used by every RLS policy in the schema
-- ---------------------------------------------------------------------------

create or replace function public.current_role_of(uid uuid default auth.uid())
returns public.user_role
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.profiles where id = uid;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and not is_suspended
  );
$$;

-- Content editors can manage the catalogue but never users, money or settings.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'content_editor') and not is_suspended
  );
$$;

create or replace function public.current_grade()
returns smallint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select grade from public.profiles where id = auth.uid();
$$;

create or replace function public.is_active_account()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and not is_suspended and deactivated_at is null
  );
$$;

-- ---------------------------------------------------------------------------
-- Referral code generation
--
-- Six characters from an unambiguous alphabet (no O/0/I/1) so a student can
-- read one off a phone screen and a friend can type it without a typo. Looped
-- rather than trusted-on-first-try because the unique index is the real
-- guarantee and collisions, while rare, are not impossible.
-- ---------------------------------------------------------------------------

create or replace function public.generate_referral_code()
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  candidate text;
  i integer;
begin
  for attempt in 1..12 loop
    candidate := '';
    for i in 1..6 loop
      candidate := candidate || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    if not exists (select 1 from public.profiles where referral_code = candidate) then
      return candidate;
    end if;
  end loop;
  -- Astronomically unlikely fallback that still cannot collide.
  return 'K' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 9));
end;
$$;

-- ---------------------------------------------------------------------------
-- auth.users -> profiles bridge
--
-- SECURITY NOTE: raw_user_meta_data is attacker-controlled. Supabase's anon
-- key is public by design, so anyone can POST directly to /auth/v1/signup with
-- whatever metadata they like — including "role": "admin". This trigger is
-- therefore the security boundary, not the application route that normally
-- calls it: it hard-codes role = 'student', re-normalises the phone number in
-- SQL, and clamps the grade. Nothing privileged is ever read from metadata.
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  meta            jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  v_full_name     text;
  v_phone         text;
  v_grade         smallint;
  v_school_name   text;
  v_school_id     uuid;
  v_referral_code text;
  v_referrer      uuid;
begin
  v_full_name := nullif(trim(meta ->> 'full_name'), '');
  v_phone     := public.normalize_et_phone(meta ->> 'phone');
  v_school_name := nullif(trim(meta ->> 'school_name'), '');

  begin
    v_grade := (meta ->> 'grade')::smallint;
  exception when others then
    v_grade := null;
  end;

  -- These are validated again in the application before signUp is called; the
  -- checks here exist for the direct-to-GoTrue path that bypasses it.
  if v_full_name is null then
    raise exception 'registration_full_name_required';
  end if;
  if v_phone is null then
    raise exception 'registration_phone_invalid';
  end if;
  if v_grade is null or v_grade not between 9 and 12 then
    raise exception 'registration_grade_invalid';
  end if;
  if v_school_name is null then
    raise exception 'registration_school_required';
  end if;

  -- Upsert the school by its normalized form so "Menelik II" and
  -- "  menelik  ii " land on one row.
  select id into v_school_id
  from public.schools
  where normalized_name = lower(regexp_replace(trim(v_school_name), '\s+', ' ', 'g'));

  if v_school_id is null then
    insert into public.schools (name) values (v_school_name)
    on conflict (normalized_name) do update set name = public.schools.name
    returning id into v_school_id;
  end if;

  -- Resolve the referral code to a referrer, ignoring it silently when it does
  -- not match anyone. A bad code must never block a registration.
  v_referral_code := nullif(upper(trim(meta ->> 'referral_code')), '');
  if v_referral_code is not null then
    select id into v_referrer
    from public.profiles
    where referral_code = v_referral_code
      and not is_suspended
      and deactivated_at is null;
  end if;

  insert into public.profiles (
    id, full_name, phone, email, grade, school_id, school_name,
    role, referral_code, referred_by
  ) values (
    new.id,
    v_full_name,
    v_phone,
    new.email,
    v_grade,
    v_school_id,
    v_school_name,
    'student',                      -- never from metadata
    public.generate_referral_code(),
    v_referrer
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Keep the profile's email mirror in step when a user changes it in auth.
create or replace function public.handle_user_email_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.email is distinct from old.email then
    update public.profiles set email = new.email where id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_email_changed on auth.users;
create trigger on_auth_user_email_changed
  after update of email on auth.users
  for each row execute function public.handle_user_email_change();

-- ---------------------------------------------------------------------------
-- Device sessions (spec section 21: one account = one active session)
--
-- Supabase's own JWT is stateless and cannot be revoked mid-flight, so single
-- session enforcement needs server-side state of its own. The cookie carries a
-- random token; only its SHA-256 hash is stored, so even an admin reading this
-- table cannot replay a student's session.
-- ---------------------------------------------------------------------------

create table if not exists public.user_sessions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  token_hash    text not null,
  device_label  text,
  user_agent    text,
  ip_address    inet,
  created_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  revoked_at    timestamptz,
  revoked_reason text
);

create unique index if not exists user_sessions_token_hash_key on public.user_sessions (token_hash);
create index if not exists user_sessions_user_active_idx
  on public.user_sessions (user_id, last_seen_at desc)
  where revoked_at is null;

-- ---------------------------------------------------------------------------
-- Audit log (spec section 34)
-- ---------------------------------------------------------------------------

create table if not exists public.audit_logs (
  id           bigint generated always as identity primary key,
  actor_id     uuid references public.profiles (id) on delete set null,
  actor_email  text,
  action       text not null,
  target_table text,
  target_id    text,
  metadata     jsonb not null default '{}'::jsonb,
  ip_address   inet,
  created_at   timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs (actor_id, created_at desc);
create index if not exists audit_logs_action_idx on public.audit_logs (action, created_at desc);

-- =============================================================================
-- Row Level Security
-- =============================================================================

alter table public.schools       enable row level security;
alter table public.profiles      enable row level security;
alter table public.user_sessions enable row level security;
alter table public.audit_logs    enable row level security;

-- Schools are public reference data: the registration form needs to suggest
-- them before the visitor has an account at all.
drop policy if exists schools_read_all on public.schools;
create policy schools_read_all on public.schools
  for select using (true);

drop policy if exists schools_staff_write on public.schools;
create policy schools_staff_write on public.schools
  for all using (public.is_staff()) with check (public.is_staff());

-- A student reads and writes exactly one profile: their own. Note the WITH
-- CHECK clause pins every field a student must not be able to grant
-- themselves — role, suspension, streak counters, total time, referral
-- lineage. Postgres evaluates it against the *post-update* row, so an attempt
-- to escalate simply fails rather than partially applying.
drop policy if exists profiles_read_own on public.profiles;
create policy profiles_read_own on public.profiles
  for select using (id = auth.uid() or public.is_staff());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and role = (select p.role from public.profiles p where p.id = auth.uid())
    and is_suspended = (select p.is_suspended from public.profiles p where p.id = auth.uid())
    and current_streak = (select p.current_streak from public.profiles p where p.id = auth.uid())
    and longest_streak = (select p.longest_streak from public.profiles p where p.id = auth.uid())
    and total_seconds = (select p.total_seconds from public.profiles p where p.id = auth.uid())
    and referral_code = (select p.referral_code from public.profiles p where p.id = auth.uid())
    and referred_by is not distinct from (select p.referred_by from public.profiles p where p.id = auth.uid())
    and grade = (select p.grade from public.profiles p where p.id = auth.uid())
  );

-- Only admins administer people. Content editors are deliberately excluded.
drop policy if exists profiles_admin_all on public.profiles;
create policy profiles_admin_all on public.profiles
  for all using (public.is_admin()) with check (public.is_admin());

-- A student may list and revoke their own sessions ("sign out my other
-- device"), but the token hash column is never exposed through the API layer.
drop policy if exists user_sessions_own on public.user_sessions;
create policy user_sessions_own on public.user_sessions
  for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists user_sessions_admin on public.user_sessions;
create policy user_sessions_admin on public.user_sessions
  for all using (public.is_admin()) with check (public.is_admin());

-- Audit logs are readable by admins and writable by nobody through the API —
-- every insert goes through a SECURITY DEFINER function so the actor cannot be
-- forged.
drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs
  for select using (public.is_admin());

create or replace function public.write_audit_log(
  p_action       text,
  p_target_table text default null,
  p_target_id    text default null,
  p_metadata     jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_email text;
begin
  select email into v_email from public.profiles where id = auth.uid();
  insert into public.audit_logs (actor_id, actor_email, action, target_table, target_id, metadata)
  values (auth.uid(), v_email, p_action, p_target_table, p_target_id, coalesce(p_metadata, '{}'::jsonb));
end;
$$;

grant execute on function public.write_audit_log(text, text, text, jsonb) to authenticated;
